# action.yml
name: 'Pushgateway POST'
description: 'Post a metric to Pushgateway'
inputs:
  pushgateway_url:  # id of input
    description: 'URL of pushgateway'
    required: true
    default: 'http://localhost:9091/metrics/'
  metric_name:
    description: "The name of the metric you want to create/update"
    required: true
    default: "metric_name"
  metric_labels:
    description: "The list of labels for your metric"
    required: false
    default: ""
outputs:
  status: # id of output
    description: 'Return status code'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
