on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: POST on Pushgateway
    steps:
      - name: POST on Pushgateway
        id: post
        uses: cirolini/hello-world-docker-action@v1.3
        with:
          pushgateway_url: 'Cirolini the boss'
          job: "JobB"
          metric_name: "Cirolini"
          metric_description: "Cirolini is the best"
          metric_labels: "{'version': '1.0'}"
      # Use the output from the `hello` step
      - name: Get the output
        run: echo "The time was ${{ steps.post.outputs.status }}"
