on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: POST on Pushgateway
    steps:
      - name: Star local Pushgateway
        run: docker run -d -p 9091:9091 prom/pushgateway
      - name: POST on Pushgateway
        id: post
        uses: cirolini/hello-world-docker-action@v1.7
        with:
          pushgateway_url: 'https://31dd-189-6-240-216.sa.ngrok.io/'
          job: "JobB"
          metric_name: "Cirolini"
          metric_description: "Cirolini is the best"
          metric_labels: "{'version': '2.0'}"
      # Use the output from the `hello` step
      - name: Get the output
        run: echo "The time was ${{ steps.post.outputs.status }}"
